//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Generic Content Page</summary>
	[PublishedContentModel("genericContentPage")]
	public partial class GenericContentPage : PublishedContentModel, IPage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "genericContentPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GenericContentPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GenericContentPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// BG Color
		///</summary>
		[ImplementPropertyType("bGColor")]
		public string BGcolor
		{
			get { return this.GetPropertyValue<string>("bGColor"); }
		}

		///<summary>
		/// Second Input Text
		///</summary>
		[ImplementPropertyType("secondInputText")]
		public IHtmlString SecondInputText
		{
			get { return this.GetPropertyValue<IHtmlString>("secondInputText"); }
		}

		///<summary>
		/// Page Main Text
		///</summary>
		[ImplementPropertyType("pageMainText")]
		public IHtmlString PageMainText
		{
			get { return Umbraco.Web.PublishedContentModels.Page.GetPageMainText(this); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Page.GetPageTitle(this); }
		}
	}
}
